### ISSUE TITLE
.env.example

### ISSUE THREAD

**Issue by stephdavid** [digitalronin/c100-training-app#5]
This file was not carried over. As a stop-gap fix I've copied the file into the local repo, it's neither added nor staged in git. Will await your instruction on how to handle.

**Comment by digitalronin** [comment]
Hi Steph
My mistake - good catch.
Please follow the same process as for any other change, i.e.;
* Create a feature branch
* Add and commit the missing file
* Push the branch to github
* Raise a PR to merge the branch
